### ISSUE TITLE
Support for FCM

### ISSUE THREAD

**Issue by kleisauke** [zendframework/ZendService_Google_Gcm#20]
Will this package get support for FCM (Firebase Cloud Messaging)?

> GCM users are strongly recommended to upgrade to FCM, in order to benefit from new FCM features today and in the future.

See: https://developers.google.com/cloud-messaging/faq

At first look, I think it's only necessary to change the URL in [this file](https://github.com/zendframework/ZendService_Google_Gcm/blob/master/library/ZendService/Google/Gcm/Client.php#L32).

``` diff
-const SERVER_URI = 'https://gcm-http.googleapis.com/gcm/send';
+const SERVER_URI = 'https://fcm.googleapis.com/fcm/send';
```

[Source](https://firebase.google.com/docs/cloud-messaging/downstream#sending_topic_messages_from_the_server)

**Comment by mwillbanks** [comment]
@kleisauke entirely possible; feel free to submit a PR.

**Comment by kleisauke** [comment]
@mwillbanks A pull request has been made for this at #25.

**Comment by andycaramba** [comment]
@mwillbanks Please, could you approve PR?

**Comment by bathan** [comment]
@mwillbanks When is this going to be downloadable via composer?

**Comment by mwillbanks** [comment]
@bathan well, if you can download it separately and functionally test it that would be great.  I am likely going to do it this weekend (I was on vacation last week and this week has been catching up on main work tasks).

**Comment by jaystepin** [comment]
@mwillbanks When are you planning to release this new FCM support update? When is this going to be downloadable via composer?

**Comment by mwillbanks** [comment]
@jaystepin I'll release it today.
