### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by odolbeau** [zendframework/ZendService_Google_Gcm#7]
Hello,

Could you please tag a new release to have #5 in stable ?
Thanks in advance !

**Comment by kdubuc** [comment]
+1

**Comment by antriver** [comment]
^

**Comment by antriver** [comment]
Temporary fix:
I've forked the repo and bumped the version. You can add this to your composer.json to use it:
    "repositories": [
        {
          "type": "vcs",
          "url": "https://github.com/antriver/ZendService_Google_Gcm.git"
        }
    ],

**Comment by slimus** [comment]
+1

**Comment by antriver** [comment]
Seriously? This is almost a year old. The fix is already there just update the version please!

**Comment by weierophinney** [comment]
release-1.0.2 tagged.
